[general]
import = [
    "themes/nord.toml"
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 11.75

[font.normal]
family = "JetBrainsMono Nerd Font"

[mouse]
hide_when_typing = true

[window]
dynamic_title = true
startup_mode = "Windowed"
decorations_theme_variant = "Dark"

[window.padding]
x = 4
y = 4
