[general]
live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 11.25

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Middle", action = "PasteSelection" }
]

[terminal]

[window]
# decorations = "None"
dynamic_title = true
startup_mode = "Windowed"
decorations_theme_variant = "Dark"

[window.padding]
x = 4
y = 4
